stages:
  create_splits:
    cmd: python scripts/create_train_test_splits.py
    deps:
    - data/03_features/fraud_dataset_engineered_v1.0.parquet
    outs:
    - data/02_processed/fraud_train_v1.0.parquet
    - data/02_processed/fraud_test_v1.0.parquet
    - data/02_processed/fraud_splits_v1.0_metadata.yaml
    params:
    - test_size
    - random_state
  feature_engineering:
    cmd: python scripts/create_featured_dataset.py
    deps:
    - data/01_raw/train_transaction.csv
    - data/01_raw/train_identity.csv
    - src/features/feature_engineering.py
    outs:
    - data/03_features/fraud_dataset_engineered_v1.0.parquet
    - data/03_features/fraud_dataset_engineered_v1.0_metadata.yaml
    - models/feature_pipeline_v1.0.pkl
    params:
    - sample_size
    - feature_selection_k
