feature_engineering:
  use_aggregation: true
  use_amount: true
  use_interactions: true
  use_temporal: true
feature_selection_k: 150
model_training:
  cv_folds: 3
  models:
  - logistic_baseline
  - logistic_advanced
  - random_forest
random_state: 42
sample_size: 50000
test_size: 0.2
